server:
  port: 8090
  context-path: /
  encoding:
    charset: UTF-8
    enabled: true
    force: true

spring:
#TODO : 추후 실제 서비스때 계정 및 패스워드 변경 필요
#TODO : 및 DB에 계정 생성 및 권한 부여 필요
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp